### ISSUE TITLE
Menu Items

### ISSUE THREAD

**Issue by Braytonio** [zhe/hugo-theme-slim#11]
How to add menu items to the "hamburger" menu? A newbie question, sorry.

**Comment by baskoroi** [comment]
You can go to the `layouts/` directory. As you can see in `index.html`, there's `{{ partial "header.html" . }}`. If you don't understand that, it means that there's a HTML partial called `header.html`. 

How do you get there? While still inside `layouts/`, get inside the `partials/` directory and open up `header.html`. Inside `<div class="nav">`, go ahead and add your links.

That's all...

**Comment by zhe** [comment]
Hi, thanks for the comments. I'm closing this issue. I'm working on new version on the v2 branch, you might be interested.
