### ISSUE TITLE
How to add tags?

### ISSUE THREAD

**Issue by creachang** [zhe/hugo-theme-slim#15]
I tried many times to add tags on articles but it doesn't work.
I put this in my markdown:
```
+++
...
[params]
    tags = "tag1"
...
+++

```
How Could I fix it?

**Comment by jostyee** [comment]
You can modify the template to meet your own needs, my way: https://github.com/jostyee/hugo-theme-slim/commit/33f2fe29839a2a4c9e858d08b82a6cedc52d56b2

**Comment by creachang** [comment]
感谢您的回覆，但其实我想问的是标签在markdown文章里面的设定，我现在在文章里面写：
```
---
title: "Sec"
date: 2017-08-19T03:54:20+08:00
Description: ""
menu: "main"
comments: true
Params:
    tags: "tag1"
---
内文...

```
然后 `hugo server` 后
没有在页面上看到任何标签，
想请问的是，是否还有要在哪里设定标签

**Comment by jostyee** [comment]
try

```
---
title: "Sec"
date: 2017-08-19T03:54:20+08:00
Description: ""
menu: "main"
comments: true
tags: [
    "tag1",
    "tag2"
]
---
```

**Comment by creachang** [comment]
oh, it works!
Thanks!
