### ISSUE TITLE
Menu would be out of order if the menu title longer

### ISSUE THREAD

**Issue by graycreate** [zhe/hugo-theme-slim#3]
![](http://77g5pl.com1.z0.glb.clouddn.com/slim-issues.png)

Your theme is awesome! Thanks for your working.
Pleasy fix this!

**Comment by zhe** [comment]
Hi @ghuiii, are you really using this looooooooong word to describe your feelings? :joy:

Back to this issue, I didn't set a width to `.nav` to keep it fluid. I'm not sure how wide the user will need for this nav, 70 or 80px? To quick fix it, I would set a width to the outer `div`, say 80px, and make the `ul` `text-overflow: ellipsis`.

```
.nav-list {
  width: 100%;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

What do you say?

**Comment by graycreate** [comment]
Not really!
But it's normal to use some like “读书笔记”，“个人感受”…… Then Slim will not work well.

**Comment by zhe** [comment]
<img width="194" alt="screen shot 2015-12-28 at 2 45 50 pm" src="https://cloud.githubusercontent.com/assets/20175/12015070/c3281fc6-ad71-11e5-8f0d-7c947379da30.png">

Alright. We can add `transform: translateX(-100%);` to move the nav to the left based on 100% of its current width.

**Comment by zhe** [comment]
Commit 50b9b8829efd054db1229923956e778e6d2c3481
