### ISSUE TITLE
Page margins in mobile mode

### ISSUE THREAD

**Issue by qugu** [zhe/hugo-theme-slim#9]
Dear Zhe,

First of all, the theme is so minimal and excellent, i'd like to thank you for it.

I've noticed that when looking at the webpage from a mobile phone, the left padding is zero sized, thus the menu is gone and the left border is gone as well. 

Could you please advise if this is intended, and what would be the best approach to improve this?

Thank you.
Timofei

**Comment by zhe** [comment]
Hi Timofei,

Thank you for the comment.
I'm gonna take some time to look into this issue.

Zhe

**Comment by bodiam** [comment]
Same here. I'm not much of a designer, so if you'd have an answer to this, it would be most appreciated! Thanks!

**Comment by bodiam** [comment]
I just checked: it's the body margin in slim.css, which is set to zero. Removing that will fix it.

**Comment by qugu** [comment]
Hi @bodiam ,
Neat fix. Thanks.

**Comment by zhe** [comment]
I'm closing this issue. Thanks! 😄
